services:
  - type: web
    name: mahzarbashi-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    plan: free
    envVars:
      - key: TELEGRAM_TOKEN
        value: 8249435097:AAGOIS7GfwBayCTSZGFahbMhYcZDFxzSGAg
